//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CpyFcDel.NET.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CpyFcDel.NET.Localization.lang_en", typeof(lang_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program will terminate in a few secs.
        /// </summary>
        internal static string app_info_1 {
            get {
                return ResourceManager.GetString("app_info_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto exit when finished properly.
        /// </summary>
        internal static string auto_exit {
            get {
                return ResourceManager.GetString("auto_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse....
        /// </summary>
        internal static string browse___ {
            get {
                return ResourceManager.GetString("browse...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Settings.
        /// </summary>
        internal static string cache_settings {
            get {
                return ResourceManager.GetString("cache_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commandline Options.
        /// </summary>
        internal static string cl_title {
            get {
                return ResourceManager.GetString("cl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CpyFcDel.NET SourceDir TargetDir  [/DW] [/DR] [/P:passes] [/AE]{0}{0}Usage:{0}  /DW{1}{1}write-cache off{0}  /DR{1}{1}read-cache off{0}  /P:passes{1}set the running counter to a certain number{0}  /AE{1}{1}auto exit program on{0}{0}Examples：{0}  CpyFcDel.NET C:\Temp1 C:\Temp2{0}  CpyFcDel.NET C:\Temp1 C:\Temp2 /DW /DR{0}  CpyFcDel.NET C:\Temp1 C:\Temp2 /P:10 /AE{0}{0}Attention：{0}  option /AE is available only if /P is set{0}.
        /// </summary>
        internal static string cl_usage {
            get {
                return ResourceManager.GetString("cl_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare:.
        /// </summary>
        internal static string compare_ {
            get {
                return ResourceManager.GetString("compare:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied: .
        /// </summary>
        internal static string copied_ {
            get {
                return ResourceManager.GetString("copied:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy:.
        /// </summary>
        internal static string copy_ {
            get {
                return ResourceManager.GetString("copy:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pass.
        /// </summary>
        internal static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit to.
        /// </summary>
        internal static string count_limit_on {
            get {
                return ResourceManager.GetString("count_limit_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pass.
        /// </summary>
        internal static string counter {
            get {
                return ResourceManager.GetString("counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Time:.
        /// </summary>
        internal static string current_time_ {
            get {
                return ResourceManager.GetString("current_time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete:.
        /// </summary>
        internal static string delete_ {
            get {
                return ResourceManager.GetString("delete:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No corresponding source directory or invalid name..
        /// </summary>
        internal static string error_info_1_src {
            get {
                return ResourceManager.GetString("error_info_1_src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No corresponding target directory or invalid name..
        /// </summary>
        internal static string error_info_1_tgt {
            get {
                return ResourceManager.GetString("error_info_1_tgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number format.
        /// </summary>
        internal static string error_info_2 {
            get {
                return ResourceManager.GetString("error_info_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the limited pass to be set must great than 0.
        /// </summary>
        internal static string error_info_3 {
            get {
                return ResourceManager.GetString("error_info_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File verification failed..
        /// </summary>
        internal static string error_info_4 {
            get {
                return ResourceManager.GetString("error_info_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue ?.
        /// </summary>
        internal static string if_continue_ {
            get {
                return ResourceManager.GetString("if_continue?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string other_settings {
            get {
                return ResourceManager.GetString("other_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Read Cache.
        /// </summary>
        internal static string read_cache_on {
            get {
                return ResourceManager.GetString("read_cache_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Directory.
        /// </summary>
        internal static string source_dir {
            get {
                return ResourceManager.GetString("source_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time:.
        /// </summary>
        internal static string start_time_ {
            get {
                return ResourceManager.GetString("start_time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status_info {
            get {
                return ResourceManager.GetString("status_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - is stopping.
        /// </summary>
        internal static string stopping {
            get {
                return ResourceManager.GetString("stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Directory.
        /// </summary>
        internal static string target_dir {
            get {
                return ResourceManager.GetString("target_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string time_duration_ {
            get {
                return ResourceManager.GetString("time_duration:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string time_info {
            get {
                return ResourceManager.GetString("time_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Write Cache.
        /// </summary>
        internal static string write_cache_on {
            get {
                return ResourceManager.GetString("write_cache_on", resourceCulture);
            }
        }
    }
}
