//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CpyFcDel.NET.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_ja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_ja() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CpyFcDel.NET.Localization.lang_ja", typeof(lang_ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プログラムは数秒後に終了する。.
        /// </summary>
        internal static string app_info_1 {
            get {
                return ResourceManager.GetString("app_info_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動終了.
        /// </summary>
        internal static string auto_exit {
            get {
                return ResourceManager.GetString("auto_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参照....
        /// </summary>
        internal static string browse___ {
            get {
                return ResourceManager.GetString("browse...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャッシュ設定.
        /// </summary>
        internal static string cache_settings {
            get {
                return ResourceManager.GetString("cache_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドプロンプト命令.
        /// </summary>
        internal static string cl_title {
            get {
                return ResourceManager.GetString("cl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CpyFcDel.NET ディレクトリ1 ディレクトリ2 [/DW] [/DR] [/P:passes [/AE]]{0}{0}使用法：{0}  /DW{1}{1}書込みキャッシュオフ{0}  /DR{1}{1}読込みキャッシュオフ{0}  /P:passes{1}{1}実行回数をpasses回にする{0}  /AE{1}{1}自動終了オン{0}{0}例：{0}  CpyFcDel.NET C:\Temp1 C:\Temp2{0}  CpyFcDel.NET C:\Temp1 C:\Temp2 /DW /DR{0}  CpyFcDel.NET C:\Temp1 C:\Temp2 /P:10 /AE{0}{0}注意：{0}  オプション/AEは、/Pが指定された時だけ有効{0}.
        /// </summary>
        internal static string cl_usage {
            get {
                return ResourceManager.GetString("cl_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 比較：.
        /// </summary>
        internal static string compare_ {
            get {
                return ResourceManager.GetString("compare:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コピーされた容量：.
        /// </summary>
        internal static string copied_ {
            get {
                return ResourceManager.GetString("copied:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コピー：.
        /// </summary>
        internal static string copy_ {
            get {
                return ResourceManager.GetString("copy:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回.
        /// </summary>
        internal static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回数を制限する.
        /// </summary>
        internal static string count_limit_on {
            get {
                return ResourceManager.GetString("count_limit_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回目.
        /// </summary>
        internal static string counter {
            get {
                return ResourceManager.GetString("counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在時刻：.
        /// </summary>
        internal static string current_time_ {
            get {
                return ResourceManager.GetString("current_time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除：.
        /// </summary>
        internal static string delete_ {
            get {
                return ResourceManager.GetString("delete:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ソースディレクトリの名前が存在しないか、ディレクトリではありません。.
        /// </summary>
        internal static string error_info_1_src {
            get {
                return ResourceManager.GetString("error_info_1_src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ターゲットディレクトリの名前が存在しないか、ディレクトリではありません。.
        /// </summary>
        internal static string error_info_1_tgt {
            get {
                return ResourceManager.GetString("error_info_1_tgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無効な数字です。.
        /// </summary>
        internal static string error_info_2 {
            get {
                return ResourceManager.GetString("error_info_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ソースディレクトリにファイルがありません。.
        /// </summary>
        internal static string error_info_2_src {
            get {
                return ResourceManager.GetString("error_info_2_src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ターゲットディレクトリがソースディレクトリと別フォルダに指定してください。.
        /// </summary>
        internal static string error_info_2_tgt {
            get {
                return ResourceManager.GetString("error_info_2_tgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1以上の整数を入れてください。.
        /// </summary>
        internal static string error_info_3 {
            get {
                return ResourceManager.GetString("error_info_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルは一致しませんでした。.
        /// </summary>
        internal static string error_info_4 {
            get {
                return ResourceManager.GetString("error_info_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 続きますか？.
        /// </summary>
        internal static string if_continue_ {
            get {
                return ResourceManager.GetString("if_continue?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 各種設定.
        /// </summary>
        internal static string other_settings {
            get {
                return ResourceManager.GetString("other_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 読込みキャッシュを有効する.
        /// </summary>
        internal static string read_cache_on {
            get {
                return ResourceManager.GetString("read_cache_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ソースディレクトリ.
        /// </summary>
        internal static string source_dir {
            get {
                return ResourceManager.GetString("source_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始時刻：.
        /// </summary>
        internal static string start_time_ {
            get {
                return ResourceManager.GetString("start_time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステータス.
        /// </summary>
        internal static string status_info {
            get {
                return ResourceManager.GetString("status_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中止.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 停止中.
        /// </summary>
        internal static string stopping {
            get {
                return ResourceManager.GetString("stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ターゲットディレクトリ.
        /// </summary>
        internal static string target_dir {
            get {
                return ResourceManager.GetString("target_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スレッド停止がリクエストされた。.
        /// </summary>
        internal static string thread_terminating {
            get {
                return ResourceManager.GetString("thread_terminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 経過時間：.
        /// </summary>
        internal static string time_duration_ {
            get {
                return ResourceManager.GetString("time_duration:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在試験時刻.
        /// </summary>
        internal static string time_info {
            get {
                return ResourceManager.GetString("time_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前回試験時刻.
        /// </summary>
        internal static string time_info_old {
            get {
                return ResourceManager.GetString("time_info_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書込みキャッシュを有効する.
        /// </summary>
        internal static string write_cache_on {
            get {
                return ResourceManager.GetString("write_cache_on", resourceCulture);
            }
        }
    }
}
